/* quetes.js — Quêtes RPG La Boucle Sauvage */
window.QUETES_RPG = [
  // ZONE 1 — Ardennes
  { id:1, zone:1, type:"collecte", title:"La Récolte des Myrtilles", reward:"+stocks lipides & antioxydants",
    lore:"Les landes acides des Ardennes en août : myrtilles à leur pic absolu. Rares à cette altitude, introuvables plus au sud.",
    objectives:["Récolter myrtilles en landes (pics mi-août)","Faire des cuirs de myrtilles (anti-diarrhéique, 6 mois de conservation)","Sécher une portion pour stocks secs"], done:false },
  { id:2, zone:1, type:"collecte", title:"Les Faînes de la Grande Hêtraie", reward:"+stocks lipides hivernaux",
    lore:"Les vieux hêtres ardennais lâchent leurs faînes triangulaires dès fin août. Torréfiées, elles se conservent 6 mois.",
    objectives:["Identifier les vieux hêtres à faînes abondantes","Récolter et décortiquer les faînes (gants — bogues piquantes)","Torréfier 10 min à sec (neutralise la fagine)","Stocker en bocal hermétique"], done:false },
  { id:3, zone:1, type:"exploration", title:"Les Vergers de Lorraine", reward:"+stocks glucides & vitamines",
    lore:"La Lorraine en août : mirabelles et quetsches dans les vergers abandonnés en bord de Moselle. Un trésor oublié.",
    objectives:["Repérer les vergers abandonnés le long de la Moselle","Récolter mirabelles au pic (mi-août)","Faire des cuirs de prunes ou sécher"], done:false },
  { id:4, zone:1, type:"survie", title:"Naviguer Offline — Zéro Réseau",
    reward:"+autonomie totale · GPS sans données mobiles",
    lore:"En forêt ardennaise, le réseau disparaît. Le projet entier repose sur des cartes offline — Brouter pour les GPX, OruxMaps ou OsmAnd pour la navigation temps réel. Maîtriser ces outils avant d'en avoir besoin.",
    objectives:["Télécharger les tuiles CyclOSM offline pour toute la zone de la boucle avant le départ","Vérifier que le GPX Brouter s'affiche correctement sans réseau","Tester le recalcul d'itinéraire en cas de route fermée","Identifier les zones de mauvaise couverture sur la carte et anticiper"],
    done:false },
  { id:5, zone:1, type:"survie", title:"L'Eau — Trouver, Évaluer, Boire",
    reward:"+autonomie hydrique totale · zéro achat",
    lore:"L'eau gratuite est partout — fontaines de village, sources, ruisseaux, lavoirs. Mais toutes ne se valent pas. Apprendre à lire une eau avant de la boire, sans matériel de filtration coûteux.",
    objectives:["Identifier les fontaines publiques potables sur OpenStreetMap (tag drinking_water=yes)","Apprendre à évaluer visuellement : eau courante > eau stagnante, amont d'élevage = risque","Technique de purification primitive si doute : ébullition 1 min (cuiseur à riz)","Repérer les sources sur IGN/OpenStreetMap avant chaque étape longue sans village"],
    done:false },
  { id:6, zone:1, type:"survie", title:"Premier Mois à Zéro Euro",
    reward:"+émancipation économique · logique budget zéro validée",
    lore:"Le premier mois teste toute la stratégie : nourriture sauvage, eau gratuite, bivouac légal, recharge électrique sans payer. Si ça marche en Ardennes et Lorraine, ça marchera partout.",
    objectives:["Recharge batterie vélo : bibliothèques, offices de tourisme, aires de camping-car (souvent gratuites), restaurants avec demande directe","Bivouac : forêt domaniale (légal 1 nuit), bords de chemin rural, avec accord propriétaire","Ne rien acheter à manger les 30 premiers jours — tenir le journal des ressources gratuites","Documenter chaque jour dans le journal du carnet : zéro dépense = quête validée"],
    done:false },
  // ZONE 2 — Morvan
  { id:7, zone:2, type:"survie", title:"La Constitution des Stocks Hivernaux", reward:"+résistance hiver · stocks complets",
    lore:"Le Morvan est la seule chance avant l'Espagne de constituer des réserves solides. Rater cette halte, c'est arriver en Ibérie sous-alimenté.",
    objectives:["Récolter faînes (Settons — hêtraies exceptionnelles)","Trouver et sécher champignons (cèpes, chanterelles, trompettes)","Lixiviation des glands 48h (lac = eau courante = rapide)","Torréfier et stocker — sacoches pleines avant Chalon"], done:false },
  { id:8, zone:2, type:"collecte", title:"Les Champignons du Granit", reward:"+protéines séchées · stocks aromatiques",
    lore:"Le granit acide du Morvan crée des conditions idéales pour les cèpes. Début septembre après pluie = jackpot.",
    objectives:["Identification formelle avant récolte (pas de doute tolété)","Sécher côté lamelles au soleil (active vitamine D)","Objectif : 500g séchés minimum pour l'hiver"], done:false },
  { id:9, zone:2, type:"exploration", title:"Cartographier les Ressources Libres",
    reward:"+réseau de points gratuits · logique nomade ancrée",
    lore:"Le Morvan est rural et peu dense. Idéal pour construire la carte mentale des ressources libres : fontaines, abris forestiers, bornes de recharge, propriétaires accueillants. Ce qui fonctionne ici fonctionnera partout.",
    objectives:["Ajouter 5 bornes de recharge gratuites découvertes sur OpenStreetMap (contribution directe)","Repérer les abris forestiers ONF (ouverts au public, légaux pour bivouac)","Identifier un agriculteur ou habitant par zone acceptant le bivouac en échange d'un service"],
    done:false },
  // ZONE 3 — Saône
  { id:10, zone:3, type:"collecte", title:"Les Noix de la Saône", reward:"+lipides & oméga 3",
    lore:"Les coteaux calcaires de Saône en octobre : noyers partout, noix qui tombent au sol. Ramassage entièrement légal.",
    objectives:["Ramasser noix tombées au sol (légal partout)","Sécher et casser — stocker les cerneaux","Repérer les pleurotes sur les peupliers des berges"], done:false },
  { id:11, zone:3, type:"exploration", title:"Les Pleurotes des Bras Morts", reward:"+protéines fraîches",
    lore:"Les peupleraies des îles de Saône sont exceptionnelles pour les pleurotes en huître. Chercher les troncs morts inclinés.",
    objectives:["Identifier les peupliers morts en bord de Saône","Récolter pleurotes (automne frais et humide = optimal)","Sécher ce qu'on ne consomme pas immédiatement"], done:false },
  { id:12, zone:3, type:"collecte", title:"Les Châtaigneraies du Pilat",
    reward:"+glucides lents · stock hiver · 2-3 jours d'autonomie",
    lore:"Le Pilat en octobre, c'est d'abord une odeur. Avant même de voir les arbres, tu sens les châtaignes au sol — cette odeur de terre humide et de sucre fermenté. Les châtaigneraies couvrent les versants entre 400 et 900m. Ici un kilo se ramasse en vingt minutes.",
    objectives:["Cibler les versants nord-est entre Pélussin et Saint-Genest-Malifaux (altitude 500-800m)","Ramasser 3-4 kg de châtaignes saines — tester flottaison dans l'eau (les creuses flottent, jeter)","Séchage à l'air dans un filet : 3-4 jours avant de les mettre en sachet","Repérer les arbres producteurs pour la prochaine boucle — noter sur OsmAnd"],
    done:false },
  { id:13, zone:3, type:"exploration", title:"Traversée du Pilat — La Route des Crêtes",
    reward:"+orientation hors réseau · bivouac forêt domaniale validé",
    lore:"Le Pilat n'est pas une étape — c'est un raccourci sauvage. Plutôt que longer l'A47 et ses zones industrielles, monter par la vallée du Gier, passer sous le Crêt de la Perdrix et redescendre sur Annonay. 40 km de plus mais 400% plus beau, plus riche et plus utile.",
    objectives:["Itinéraire : Givors → vallée du Gier → Pélussin → cols → Annonay (éviter les crêtes > 1200m avec vélo chargé)","Tester la navigation 100% offline sur ce segment : OruxMaps + tuiles CyclOSM pré-téléchargées","Bivouac en forêt domaniale ONF (légal 1 nuit, s'écarter des sentiers balisés)","Identifier une fontaine ou source pour la nuit — tagger sur OpenStreetMap"],
    done:false },
  { id:14, zone:3, type:"survie", title:"Le Tournant — Premiers Stocks Lourds", reward:"⭐ TRANSITION — Mode hiver enclenché",
    lore:"Lyon, début octobre. C'est ici que le voyage change de nature. Fini ramasser pour manger ce soir — commence ramasser pour survivre dans deux mois. La Saône a donné des noix et des pleurotes. Il faut repartir chargé.",
    objectives:["Constituer un stock minimum : 500g noix + champignons séchés + prunelles","Sécher et conditionner tout l'excédent en sachets ziploc étanches","Faire l'inventaire complet des sacoches — vider ce qui est inutile pour faire de la place","Calculer les prochaines zones stocks : Périgord châtaignes (3 semaines), Gascogne protéines (5 semaines)"], done:false },
  // ZONE 4 — Cévennes
  { id:15, zone:4, type:"collecte", title:"La Châtaigne des Cévennes", reward:"+stocks glucides & énergie",
    lore:"Les châtaigneraies cévenoles sont les plus productives de France. Octobre = pic. Les châtaigniers en forêt domaniale = cueillette libre.",
    objectives:["Localiser les châtaigneraies domaniales","Récolter châtaignes (objectif : 3kg séchés)","Sécher ou faire de la farine — conservation 6 mois"], done:false },
  { id:16, zone:4, type:"collecte", title:"Les Trompettes Noires", reward:"+umami & vitamines B",
    lore:"Les chênaies calcaires des Cévennes en octobre : trompettes de la mort en colonies denses. Séchées, elles concentrent leur saveur.",
    objectives:["Trouver colonies de trompettes sous les chênes","Sécher intégralement — réduire de 90% du poids","Stocker en sachet hermétique"], done:false },
  { id:17, zone:4, type:"exploration", title:"Les Noyeraies du Périgord", reward:"+lipides & oméga 3",
    lore:"Les bords de Dordogne en octobre : noyeraies immenses, noix tombées en quantité. Le Périgord Noir est le pays de la noix.",
    objectives:["Longer la Dordogne jusqu'à Bergerac","Ramasser noix au sol sous les noyers (légal)","Constituer réserve de 2kg de cerneaux secs"], done:false },
  // ZONE 5 — Arcachon
  { id:18, zone:5, type:"survie", title:"La Halte des Protéines", reward:"+B12 · zinc · fer · immunité hivernale",
    lore:"Le Bassin d'Arcachon est la dernière source de protéines animales gratuites avant le Portugal. Deux jours ici peuvent changer tout l'hiver.",
    objectives:["Repérer les zones non-concédées à marée basse","Récolter huîtres sur rochers (couteau + gants)","Récolter palourdes dans le sable","Manger à satiété — B12 et zinc pour les semaines à venir"], done:false },
  { id:19, zone:5, type:"survie", title:"Le Passage des Pyrénées", reward:"+exploration · déblocage Zone 6",
    lore:"Col d'Ibañeta, 1000m, novembre. Route goudronnée toute l'année. La voie haute est fermée. Prendre la voie Napoléonienne.",
    objectives:["Recharger batterie à Saint-Jean-Pied-de-Port","Vérifier météo col (vent, verglas)","Passer par Valcarlos — route N-135 goudronnée","Descendre vers Donostia et la côte"], done:false },
  // ZONE 6 — Cantabrique
  { id:20, zone:6, type:"collecte", title:"Les Percebes de la Côte Sauvage", reward:"+protéines complètes · zinc · iode",
    lore:"Les percebes poussent sur les rochers les plus exposés aux vagues. Cueillette périlleuse, récompense incomparable.",
    objectives:["Attendre la marée basse (au moins -0.5m)","Identifier rochers exposés avec percebes","Cueillir avec un couteau solide (gants épais indispensables)","Ne jamais tourner le dos à la mer"], done:false },
  { id:21, zone:6, type:"collecte", title:"Le Jackpot des Asturies", reward:"+stocks glucides · champignons tardifs",
    lore:"Cangas de Onís, cœur des châtaigneraies asturiennes. Novembre = pic absolu. Les vieux châtaigniers centenaires ne demandent qu'à être récoltés.",
    objectives:["Détour vers Cangas de Onís (vallée intérieure)","Récolter châtaignes asturiennes (grosses et douces)","Champignons sous chênaies humides (boletus, chanterelles tardives)","Sécher châtaignes + champignons avant retour côte"], done:false },
  { id:22, zone:6, type:"exploration", title:"Les Rías de Galice", reward:"+protéines · déblocage Zone 7",
    lore:"Les Rías Baixas de Vigo : la plus grande densité de coquillages sauvages d'Europe. Moules géantes, palourdes, huîtres. Faire le plein avant le Portugal.",
    objectives:["Atteindre Vigo et les Rías Baixas","Récolter moules géantes sur rochers à marée basse","Ramasser palourdes dans sable zones libres","Sécher algues Porphyra (nori atlantique)"], done:false },
  // ZONE 7 — Portugal
  { id:23, zone:7, type:"exploration", title:"La Ria d'Aveiro", reward:"+protéines · B12 · fer",
    lore:"La plus grande lagune salée du Portugal. À marée basse, les palourdes (amêijoas) affleurent dans le sable des zones non-concédées.",
    objectives:["Atteindre Aveiro par la côte","Reconnaître les zones non-concédées (signalétique)","Récolter palourdes à mains nues à marée basse","Tenter la pêche à l'anguille dans les chenaux"], done:false },
  { id:24, zone:7, type:"collecte", title:"Les Pignons de la Serra da Gardunha", reward:"+lipides denses · stocks majeurs",
    lore:"Serra da Gardunha : pignons de pin parasol tombés au sol, châtaignes tardives, lactaires délicieux. Le jackpot hivernal du Portugal.",
    objectives:["Quitter la côte à Coimbra vers l'est","Atteindre la Serra da Gardunha (détour 2 jours)","Extraire pignons des cônes (chaleur + pierre)","Récolter châtaignes tardives + lactaires sous les pins","Objectif : 500g pignons torréfiés"], done:false },
  { id:25, zone:7, type:"collecte", title:"Les Oranges de Tomar", reward:"+vitamine C · stocks aromatiques",
    lore:"La vallée du Nabão est jalonnée d'orangeraies semi-abandonnées. Oranges amères, citrons, kakis translucides en décembre.",
    objectives:["Longer le Nabão depuis la Serra","Récolter oranges amères tombées (Citrus aurantium)","Sécher les zestes (vitamine C concentrée — stocks 1 an)","Kakis translucides = ultra-sucrés en décembre"], done:false },
  // ZONE 8 — Lagos
  { id:26, zone:8, type:"exploration", title:"La Côte Vicentine Sauvage", reward:"+iode · algues · percebes",
    lore:"Le Parc Naturel de la Côte Vicentine en janvier : la côte la plus sauvage d'Europe occidentale. Quasi-déserte, battue par l'Atlantique.",
    objectives:["Longer la côte depuis Comporta vers le sud","Récolter algues à marée basse (Laminaria, Porphyra, Chondrus)","Percebes sur rochers exposés du cap Sagres","Sécher Laminaria : poudre d'iode pour toute la saison"], done:false },
  { id:27, zone:8, type:"survie", title:"L'Arrivée à Lagos", reward:"⭐ ACCOMPLISSEMENT MAJEUR — Mi-boucle",
    lore:"Lagos, mi-janvier. Les amandiers fleurissent blanc et rose. La Ria de Alvor est couverte de palourdes. Mode slow. La boucle est à mi-chemin.",
    objectives:["Atteindre Lagos — Ria de Alvor","Installer bivouac longue durée (2-3 semaines)","Reconstituer tous les stocks pour le retour","Observer les amandiers en fleurs mi-janvier"], done:false },
  { id:28, zone:8, type:"exploration", title:"Bilan Mi-Boucle — Lagos",
    reward:"⭐ MI-PARCOURS — Données réelles pour la 2ème moitié",
    lore:"Lagos, mi-janvier. La mi-boucle. C'est le moment de tout mesurer — pas pour se féliciter, mais pour ajuster la 2ème moitié. Ce qui a fonctionné, ce qui a manqué, ce que le corps dit.",
    objectives:["Bilan stocks : inventaire complet des sacoches — qu'est-ce qui manque pour le retour ?","Bilan corps : poids estimé, énergie, cycle hormonal depuis le départ — noter les changements","Bilan vélo : batterie (capacité réelle après 5 mois ?), freins, chaîne, pneus — prévoir pièces","Bilan budget : total dépensé depuis août — recalibrer si nécessaire","Bilan zones retour : identifier les 3 étapes les plus critiques pour les protéines sur les 4 mois à venir"],
    done:false },
  // ══ RETOUR ══
  { id:29, zone:9, type:"collecte", title:"Les Asperges de l'Alentejo", reward:"+protéines végétales · vitamines printanières",
    lore:"Asparagus aphyllus pousse dans les garrigues d'Alentejo dès février. Fine, tendre, sauvage — rien à voir avec l'asperge cultivée.",
    objectives:["Reconnaître Asparagus aphyllus (tiges fines, buissonnant)","Récolter les jeunes pousses de 10-15cm (avant qu'elles durcissent)","Manger frais ou sécher pour stocks"], done:false },
  { id:30, zone:9, type:"collecte", title:"Les Percebes du Cap Sagres", reward:"+protéines complètes · iode · zinc",
    lore:"Les rochers du Cap Saint-Vincent en janvier : les conditions les plus exposées de la péninsule. Les percebes y sont exceptionnels.",
    objectives:["Attendre marée basse sous -0.8m","Rochers exposés côté Atlantique uniquement","Ne jamais tourner le dos aux vagues — dangers réels","Objectif : 500g frais"], done:false },
  { id:31, zone:9, type:"exploration", title:"Remontée des Rías Galiciennes", reward:"+protéines · déblocage Zone 10",
    lore:"Porto → Vigo → Pontevedra : les rías galiciennes en février sont quasi-désertes. Moules géantes, huîtres sauvages, palourdes à profusion.",
    objectives:["Longer la côte de Porto à Vigo","Récolter moules et palourdes dans zones libres","Sécher Porphyra (nori) sur les rochers plats","Passer la frontière espagnole à Tui/Valença"], done:false },
  { id:32, zone:10, type:"collecte", title:"Les Oursins de Galice", reward:"+lipides · vitamines · iode",
    lore:"Galice, février-mars : les oursins (erizos) sont au pic absolu de leur saison. Les gonades (parties comestibles) sont pleines et crémeuses.",
    objectives:["Repérer les zones rocheuses peu profondes","Cueillir à marée basse avec gants épais","Ouvrir avec ciseaux — consommer les 5 gonades orange","Récolte raisonnée (laisser les petits)"], done:false },
  { id:33, zone:10, type:"collecte", title:"L'Ail des Ours Cantabrique", reward:"+antibiotique naturel · stocks aromatiques",
    lore:"Les forêts humides de Galice et d'Asturies en mars : l'ail des ours (Allium ursinum) tapisse le sol des chênaies. Odeur inimitable.",
    objectives:["Identifier à l'odeur ail (ne pas confondre avec muguet — toxique)","Récolter feuilles avant floraison (mars = pic)","Faire du pesto : feuilles + huile + noisettes","Sécher feuilles restantes pour stocks"], done:false },
  { id:34, zone:10, type:"survie", title:"La Traversée Cantabrique", reward:"+exploration · vent dans le dos · déblocage Zone 11",
    lore:"La côte cantabrique vers l'est : cap 090°, vent d'ouest dominant dans le dos. Santander, Bilbao, San Sebastián. Le retour prend de la vitesse.",
    objectives:["Longer la côte — cap est, vent dans le dos","Étape Santander : moules et huîtres baie","Étape Bilbao : marché — derniers achats ibériques","Franchir la frontière franco-espagnole à Hendaye"], done:false },
  { id:35, zone:11, type:"collecte", title:"Le Retour des Orties", reward:"+fer · chlorophylle · protéines végétales",
    lore:"Les berges de l'Adour à Bayonne en mars : orties en pleine croissance, tendres et riches. Après 6 mois d'Ibérie, retrouver les plantes françaises.",
    objectives:["Récolter orties jeunes (gants — cueillir les 4-6 premières feuilles)","Décoction ou soupe chaude — réhydratation minérale","Sécher l'excédent pour stocks"], done:false },
  { id:36, zone:11, type:"collecte", title:"Les Huîtres d'Arcachon", reward:"+zinc · B12 · retour aux sources",
    lore:"Le Bassin d'Arcachon au retour — mars/début avril. Les zones non-concédées à marée basse. Bouclage émotionnel du cycle côtier.",
    objectives:["Retrouver les zones non-concédées du bassin","Récolter huîtres creuses sur rochers","Palourdes dans le sable vaseux","Salicorne qui commence à pousser dans les marais"], done:false },
  { id:37, zone:12, type:"collecte", title:"Le Cresson du Marais Poitevin", reward:"+vitamine C · fer · antioxydants",
    lore:"Les canaux du Marais Poitevin en avril : le cresson sauvage (Nasturtium officinale) y est abondant. Eau courante propre = récolte sûre.",
    objectives:["Identifier eau courante propre (pas en aval d'élevage)","Récolter Nasturtium officinale (feuilles rondes, goût piquant)","Consommer frais ou en jus","Oseille sauvage dans les prairies : acidité et vitamine C"], done:false },
  { id:38, zone:12, type:"collecte", title:"Les Bouchots de Noirmoutier", reward:"+protéines · B12 · fer",
    lore:"La Baie de Bourgneuf en avril : les moules de bouchot à leur meilleur. Et les premières salicornes de l'année dans les marais salants.",
    objectives:["Longer la côte de Noirmoutier","Récolter moules sur rochers et pieux exposés","Premières salicornes (tiges de 3-5cm, tendres)","Huîtres Marennes-Oléron en zones libres"], done:false },
  { id:39, zone:13, type:"collecte", title:"La Criste Marine des Falaises", reward:"+iode · aromatique · vitamines",
    lore:"Crithmum maritimum — la samphire des falaises bretonnes. Goût intense de mer et d'épice. Pousse sur les rochers inaccessibles aux moutons et aux touristes.",
    objectives:["Identifier Crithmum maritimum (ombelles blanches, feuilles charnues bleu-vert)","Récolter sur falaises et rochers côtiers","Goût unique : saler ou sécher pour condiment","Présente sur toute la côte bretonne mai-juin"], done:false },
  { id:40, zone:13, type:"survie", title:"L'Apogée des Algues Bretonnes", reward:"+iode · protéines · stocks majeurs",
    lore:"La Bretagne en mai est la capitale française des algues. Laminaria, Porphyra, Chondrus crispus, Ulva, Himanthalia. Une pharmacie minérale à marée basse.",
    objectives:["Identifier 5 espèces d'algues comestibles","Laminaria digitata : sécher et réduire en poudre (iode pour 3 mois)","Porphyra : sécher en feuilles (nori breton)","Constituer stocks d'algues pour les dernières semaines"], done:false },
  { id:41, zone:13, type:"exploration", title:"Les Araignées de Mer du Finistère", reward:"+protéines complètes · zinc · B12",
    lore:"Mai en Bretagne : les araignées de mer (Maja squinado) reviennent vers la côte pour muer. Faciles à attraper à marée basse dans les mares rocheuses.",
    objectives:["Marée basse de fort coefficient (>90)","Mares rocheuses profondes du Finistère","Attraper à la main ou au filet simple","Cuire à l'eau de mer — consommer immédiatement"], done:false },
  { id:42, zone:14, type:"collecte", title:"L'Aster Maritime de la Baie de Somme", reward:"+minéraux · aromatique · fin de boucle",
    lore:"Les prés salés de la Baie de Somme en mai : l'aster maritime (Aster tripolium) à son pic absolu. Saveur iodée intense, texture croquante.",
    objectives:["Atteindre les prés salés de Saint-Valery-sur-Somme","Récolter Aster tripolium (fleurs mauves, feuilles charnues)","Salicorne abondante dans l'estuaire","Moules sur les pieux de la baie"], done:false },
  { id:43, zone:14, type:"survie", title:"Le Retour à Artemps", reward:"🏆 ACCOMPLISSEMENT TOTAL — La Boucle est Bouclée",
    lore:"Les derniers kilomètres sur le Canal de la Somme. Les haies de Picardie en mai : fleurs de sureau, orties en fleurs, fraises des bois. Artemps au bout du chemin. ~10 000 km. La boucle est bouclée.",
    objectives:["Longer le Canal de la Somme depuis Abbeville","Récolter fleurs de sureau (Sambucus nigra — pic mai)","Premières fraises des bois dans les haies","Arriver à Artemps — fermer la boucle"], done:false },
  // ══ INTER-BOUCLES — Protéines & Iode en continu ══
  { id:44, zone:15, type:"terrain", title:"🛤️ Liaison Artemps → Creuse — Champagne & Berry",
    reward:"+axe Champagne connu · asperges · ail des ours · 13 jours",
    lore:"La clé : rester à l'est de 2.8°E pour contourner Paris par l'est. Laon → Reims → Épernay → Troyes → Auxerre → Nevers → Montluçon. Chaque vallée livre sa ressource.",
    objectives:["Asperges sauvages sur les coteaux calcaires du Laonnois — noter les spots GPS","Ail des ours dans les sous-bois de l'Yonne (Auxerre) — récolter si encore présent","Sureau en fleurs sur les berges de Marne (Épernay) — ombelles pour infusion","Écrevisses signal dans l'Allier dès Nevers — premier test nocturne à l'épuisette","Documenter bivouac îles de Loire — conditions, accès, eau potable"],
    done:false },
  { id:45, zone:15, type:"terrain", title:"🌲 Creuse — Installation & Écrevisses (Juin)",
    reward:"+protéines animales fraîches · écrevisses libres · truites · spots girolles",
    lore:"L'écrevisse signal est invasive — pêche libre toute l'année, sans quota, sans licence. Les gorges de la Creuse et de la Sédelle en sont pleines. Pêche de nuit à la lampe torche.",
    objectives:["Cartographier les zones à écrevisses : Creuse entre Fresselines et Crozant, Sédelle","Session nocturne : lampe torche + épuisette — objectif 500g par sortie","Truites fario dans la Sédelle — vérifier réglementation 1ère catégorie locale","Girolles : inspecter forêt de Chabrières après premières pluies de juin","Installer bivouac fixe en forêt domaniale — noter fontaines et points d'eau"],
    done:false },
  { id:46, zone:15, type:"terrain", title:"🫐 Millevaches — Myrtilles & Isolement (Juillet)",
    reward:"+myrtilles stock · cuirs longue durée · cèpes d'été · isolement total",
    lore:"Le plateau de Millevaches en juillet : quasi personne, des myrtilles à perte de vue entre 700 et 900m. Le moment de constituer les stocks d'antioxydants pour l'hiver au Portugal.",
    objectives:["Myrtilles : session intensive début juillet — objectif 2kg frais pour cuirs","Faire des cuirs de myrtilles (Omnia ou soleil) — 2kg frais = ~300g cuir = 3 mois stock","Cèpes d'été (Boletus aestivalis) en forêt de Chabrières — séchage au soleil","Lac de Vassivière : pêche brochet et perche sur rives nord — séchage si excédent","Journal de mi-parcours : 3 ressources les plus importantes depuis Artemps"],
    done:false },
  { id:47, zone:15, type:"terrain", title:"🌰 Tronçais — Noisettes & Départ (Début août)",
    reward:"+noisettes stock · mûres · carpes · recalage calendrier départ",
    lore:"La forêt de Tronçais (10 600 ha) marque la fin du séjour Creuse. Les premières noisettes tombent mi-août en lisière. C'est le signal du départ pour la remontée vers Artemps.",
    objectives:["Noisettes : inspecter lisières est de Tronçais — premières chutes mi-août","Mûres sauvages : pic sur toutes les haies — récolter 1kg pour cuirs","Étangs de Tronçais : pêche aux carpes et brèmes — dernière session protéines fraîches","Bilan Creuse dans le journal : ressources trouvées, spots GPS, manques identifiés","Vérifier état du vélo et matériel avant remontée — 550 km vers Artemps"],
    done:false },
  { id:48, zone:15, type:"terrain", title:"🏔️ Remontée Tronçais → Artemps — Allier & Marne",
    reward:"+sureau Marne · houblon Aisne · retour mi-août · re-départ boucle 2",
    lore:"Le retour est en miroir de l'aller — même axe, sens inverse. Tronçais → Moulins → Decize → Auxerre → Troyes → Épernay → Soissons → Artemps. Les bivouacs sont connus.",
    objectives:["Sureau noir en baies sur les berges de Marne (Épernay, Château-Thierry) — sirop ou séchage","Houblon sauvage sur les haies et bords d'Aisne entre Soissons et Artemps","Mûres : ramasser sur tout le trajet — stock de route","Être à Artemps avant le 20 août — fenêtre re-départ boucle 2","Inventaire stock complet : lister ce qui manque pour la prochaine grande boucle"],
    done:false },
  { id:49, zone:15, type:"survie", title:"La Règle des 2 Jours — Permanente",
    reward:"+logique nomade · zéro carence iode",
    lore:"Règle fondamentale du nomadisme permanent : jamais à plus de 2 jours d'une côte ou rivière poissonneuse. Iode et protéines animales fraîches ne se stockent que sur 3-4 jours.",
    objectives:["Planifier les étapes en gardant cette contrainte visible sur la carte","En cas d'éloignement forcé : activer la poudre de Laminaria (1g/jour)","Eau douce : prioriser les rivières avec visibilité de fond (eau claire = poissons)"],
    done:false },
  // ══ QUÊTE JOURNALIÈRE ══
  { id:50, zone:0, type:"quotidienne", title:"⚡ Borne du Jour — Recharge Gratuite",
    reward:"+autonomie électrique · zéro dépense énergie",
    lore:"La contrainte silencieuse de tout le projet : le Cyrusher Kommoda 3 doit être rechargé. Chaque jour sans borne est un jour de range anxiety. Chaque borne trouvée gratuitement est une victoire.",
    objectives:["Identifier la prochaine borne gratuite sur l'itinéraire (OpenStreetMap, PlugShare, demande directe)","Types prioritaires : bibliothèques, mairies, offices de tourisme, aires camping-car, hôtels de ville","En zone rurale : demander directement (boulangerie, bar, ferme) — taux d'acceptation >80%","Documenter la borne dans le journal : lieu + type + remarques pour la prochaine boucle"],
    done:false },
  // ══ ZONE 16 — ROUE DE L'ANNÉE ══
  { id:51, zone:16, type:"witch", title:"🕯️ Imbolc — Le Feu qui Revient",
    reward:"1er-2 février · Galice · Rías Baixas · Première lumière",
    lore:"La Galice en février : l'air sent le varech et le feu de bois. La lumière revient d'un quart d'heure par jour. Les percebes sont au pic sur les rochers battus. Imbolc n'est pas une fête du chaud — c'est une fête du possible.",
    objectives:[
      "Percebes ou moules : récolter sur les rochers galiciens — protéines marines au pic hivernal",
      "Asperges sauvages (Asparagus acutifolius) : premières tiges en Galice dès fin janvier — noter le spot GPS",
      "Observer le lever du soleil sur l'Atlantique galicien — noter heure exacte, la lumière revient",
      "Journal de boucle : écrire les 3 priorités terrain pour la saison qui commence",
      "Rituel feu : allumer un feu au bivouac ce soir sur la côte galicienne — observer la flamme 10 minutes"
    ], done:false },
  { id:52, zone:16, type:"witch", title:"🥚 Ostara — L'Équilibre du Printemps",
    reward:"~20 mars · Côte Basque ou Landes · Équinoxe",
    lore:"Jour et nuit parfaitement équilibrés. Sur la Côte Basque et dans les Landes, le printemps explose avant le nord : ail des ours en tapis dans les sous-bois humides dès mars. Repas complet du terrain : c'est le test de la saison.",
    objectives:[
      "Ail des ours basque : identification certaine (odeur ail en froissant = bon, odeur neutre = muguet toxique) — récolter 200g minimum",
      "Repas complet zéro achat : ail des ours + ortie + coquillage ou poisson côte basque / landes",
      "Observer lever et coucher du soleil — noter heures exactes, confirmer l'équinoxe ressenti",
      "Cueillette symbolique : une plante de chaque couleur disponible ce jour, noter dans le carnet",
      "Coordonnées GPS : marquer les tapis d'ail des ours pour la prochaine boucle"
    ], done:false },
  { id:53, zone:16, type:"witch", title:"🔥 Beltane — Le Sommet du Printemps",
    reward:"1er mai · Côte Bretagne ou Marais Poitevin · Sève maximale",
    lore:"Fenêtre de 10 jours maximum pour les fleurs d'aubépine. La sève est au pic. Les anciens disaient que la rosée de Beltane soigne — laisse les plantes mouillées, mange-les sans sécher.",
    objectives:[
      "Aubépine en fleur : récolter les ombelles fraîches (fenêtre 2 semaines max fin avril-début mai) — infusion cardiotonique du soir",
      "Sureau en fleur si disponible : fleurs fraîches en beignets ou sirop de survie concentré",
      "Inventaire stock complet avant phase côtière : noter ce qui manque",
      "Rosée du matin : à l'aube, laisser les mains mouillées de rosée sur les feuilles — contact sensoriel avec la sève",
      "Bivouac en lisière de forêt fleurie — nuit sous les étoiles si sec"
    ], done:false },
  { id:54, zone:16, type:"witch", title:"☀️ Litha — Le Solstice d'Été",
    reward:"~21 juin · Inter-boucles · Creuse ou Millevaches · Pic médicinal",
    lore:"La nuit la plus courte, sur le plateau de Millevaches ou dans les gorges de la Creuse. La teneur en hypéricine du millepertuis est maximale exactement au solstice. Après, ça redescend. Une seule chance par an — ne pas rater la fenêtre.",
    objectives:[
      "Millepertuis : cueillir boutons floraux et fleurs ouvertes EXACTEMENT au solstice ou ±2 jours — jus rouge en écrasant le bouton = bon signe — sécher à l'ombre immédiatement",
      "Girolles Creuse : après les premières pluies de juin, inspecter les talus moussus en forêt de Chabrières — noter les spots",
      "Plantain lancéolé : récolter et sécher — anti-inflammatoire respiratoire pour l'hiver Portugal",
      "Observer le lever du soleil depuis le plateau — noter heure et direction exactes depuis le bivouac",
      "Inventaire médicinal : classer et étiqueter tout le séchage accumulé depuis Imbolc"
    ], done:false },
  { id:55, zone:16, type:"witch", title:"🌾 Lughnasadh — La Première Moisson",
    reward:"1er août · Millevaches ou Tronçais · Bilan inter-boucles",
    lore:"La première moisson sur le plateau. Les myrtilles sont au pic, les premières noisettes tombent à Tronçais. Pas une fête de l'abondance — une fête de la mesure. Qu'est-ce que tu as appris ? Qu'est-ce qui manque pour la 2ème boucle ?",
    objectives:[
      "Myrtilles Millevaches : dernière récolte intensive avant de quitter le plateau — faire des cuirs pour le stock",
      "Noisettes Tronçais : premières chutes mi-août sur les lisières de la forêt domaniale — stock lipides",
      "Inventaire stock complet avant départ boucle 2 : lister les manques critiques",
      "Bilan inter-boucles dans le journal : 3 réussites terrain, 3 erreurs, 3 ajustements pour la boucle 2",
      "Définir les 3 priorités nutritionnelles pour août-septembre (début phase Ardennes boucle 2)"
    ], done:false },
  { id:56, zone:16, type:"witch", title:"🍂 Mabon — L'Équinoxe de l'Abondance",
    reward:"~22 septembre · Morvan ou Beaujolais · Grand stock automnal",
    lore:"Le grand tournant. Les noix tombent, les châtaignes s'ouvrent, les champignons explosent après la pluie. C'est maintenant ou jamais pour constituer le stock qui tiendra jusqu'en Portugal.",
    objectives:[
      "Châtaignes : objectif 2kg séchées ou torréfiées — cartographier les châtaigniers dans la zone",
      "Noix : objectif 500g cerneaux séchés — graisses essentielles pour les mois froids à venir",
      "Champignons : sécher 200g minimum — cèpes, chanterelles, trompettes selon disponibilité",
      "Cynorrhodons : repérer les rosiers sauvages, attendre après première gelée pour max vitamine C",
      "GPS des meilleurs arbres (noyers, châtaigniers, poiriers sauvages) — notes pour boucle 3"
    ], done:false },
  { id:57, zone:16, type:"witch", title:"🕸️ Samhain — Le Voile entre les Mondes",
    reward:"31 octobre · Cévennes ou Périgord · Dernier grand feu",
    lore:"La végétation se retire mais pas tout. Les prunelles deviennent douces après la première gelée. Les trompettes de la mort arrivent. Les racines concentrent leurs sucres. Fête du retrait — et de ce qui reste.",
    objectives:[
      "Prunelles après première gelée : goûter la transformation amertume → douceur — macération ou manger directement",
      "Racine de bardane : creuser, laver, cuire à l'eau 20min — féculent de secours, noter les sites GPS",
      "Trompettes de la mort : reconnaître avec certitude (gris-noir, creux, odeur agréable) — sécher immédiatement",
      "Bilan champignons de la saison : espèces, quantités, lieux dans le journal",
      "Bivouac de Samhain : grand feu si conditions sèches — écrire la liste de ce qu'on laisse derrière"
    ], done:false },
  { id:58, zone:16, type:"witch", title:"❄️ Yule — Le Solstice d'Hiver",
    reward:"~21 décembre · Portugal · Lagos ou Alentejo · Nuit la plus longue",
    lore:"La nuit la plus longue de l'année, en Portugal. Le romarin est en fleur sur les garrigues. Les oranges amères pendent aux arbres. La lumière va revenir — c'est la promesse de Yule.",
    objectives:[
      "Observer le lever du soleil au solstice depuis un point haut — noter heure et direction exactes",
      "Romarin en fleur : cueillette et séchage immédiat — pic de concentration en huile essentielle au solstice",
      "Oranges amères sauvages (Portugal, bords de route) : zestes séchés, décoction digestive et vitamine C",
      "Repas complet depuis le terrain local : poisson si côte accessible + plantes côtières Portugal",
      "Journal de fin de boucle : bilan complet — stocks restants, santé, réussites, ajustements boucle suivante"
    ], done:false },
];
