/* trajet-b.js — Artemps -> Hendaye (Tracé B)
   TRAJET_B · 6 phases · ~1790km · Ardèche/Corbières/Ariège
*/

window.TRAJET_B = {
  titre: 'Artemps → Hendaye — Variante B',
  sous_titre: 'Ardèche · Corbières · Ariège · ~1 790 km · 68–74 jours',
  km_total: 1790,
  logique: '82% voies séparées · Ardèche châtaignes · Corbières glands · Pyrénées piémont',
  phases: [
    {
      num: 1, label: 'PARTIE 1 — MI-AOÛT — Artemps → Vesoul',
      mois: 'Mi-août', color: '#2d5c8a', km: '~550 km', jours: '~17 j',
      intro: 'Traversée du nord via canaux et voies vertes. Ardennes, Meuse, Moselle, Canal des Vosges. 82% de voies séparées.',
      etapes: [
        { nom: 'Artemps → Chauny → Noyon', km: '~55 km / 2 j',
          voies: ['Chemins agricoles','Berge Oise','VV Oise'],
          note: 'Quitter Artemps par chemins agricoles vers Ognes. Longer l\'Oise rive gauche sur halage non goudronné. Voie verte jusqu\'à Noyon.',
          cueil: ['Mûres — haies et lisières : pic absolu','Sureau noir — baies mûres','Orties jeunes','Framboises sauvages — fin de saison'],
          biv: 'Berges de l\'Oise entre Chauny et Noyon.' },
        { nom: 'Noyon → Berry-au-Bac (Canal Oise–Aisne)', km: '~60 km / 2 j',
          voies: ['Canal Oise–Aisne halage','VV Chemin des Dames'],
          note: 'Halage canal depuis Noyon. VV Chemin des Dames — ancienne voie ferrée, asphalte lisse, zéro voiture.',
          cueil: ['Mûres — haies en lisière : abondantes','Noisettes — début de maturité','Sureau noir'],
          biv: 'Écluses du canal — eau potable garantie.' },
        { nom: 'Berry-au-Bac → Rethel (Canal Aisne–Marne)', km: '~65 km / 2 j',
          voies: ['Canal Aisne–Marne halage','Pistes ONF Argonne'],
          note: 'Halage canal de Berry à Vouziers. Option forêt de l\'Argonne — pistes ONF non balisées, GPS indispensable.',
          cueil: ['Chanterelles — Forêt Argonne si pluies','Russules comestibles','Bolet bai'],
          biv: 'Forêt de l\'Argonne entre Binarville et Florent.' },
        { nom: 'Rethel → Monthermé (Ardennes)', km: '~65 km / 2 j',
          voies: ['Canal Ardennes halage','Pistes ONF Ardennes'],
          note: 'Canal des Ardennes jusqu\'au Chesne. Pistes ONF vers Bogny et Monthermé — tronçon le plus sauvage du nord.',
          cueil: ['Chanterelles — versants Ardennes','Bolet bai','Mûres — lisières'],
          biv: 'Forêt de la Pointe entre Bogny et Monthermé.' },
        { nom: 'Monthermé → Givet (EuroVelo 19)', km: '~50 km / 2 j',
          voies: ['EuroVelo 19','Berge Meuse'],
          note: 'EV19 rive française — méandres de la Meuse, falaises calcaires. Option Belgique (Dinant) si météo mauvaise.',
          cueil: ['Sureau noir — pic absolu','Menthe aquatique','Bolets bais'],
          biv: 'Sous la Citadelle de Givet.' },
        { nom: 'Givet → Verdun (Trans-Ardennes + Meuse)', km: '~110 km / 3 j',
          voies: ['Trans-Ardennes gravier','Halage Meuse','Chemins militaires WW1'],
          note: 'Longer la Meuse sur halage gravier. Secteur Stenay–Dun-sur-Meuse : chemins militaires WW1, grandiose et désert.',
          cueil: ['Mûres — berges Meuse : très abondantes','Cèpes si pluies récentes','Noisettes'],
          biv: 'Rives Meuse secteur Stenay.',
          warn: '~8% D-routes — rive belge recommandée pour l\'éviter.' },
        { nom: 'Verdun → Épinal (VV Moselle)', km: '~145 km / 4 j',
          voies: ['VV Moselle 100% séparée','Canal Marne-au-Rhin'],
          note: 'VV Moselle — meilleur tronçon du nord. 100% séparée de Toul à Épinal.',
          cueil: ['Noisettes — mûres sur berges Moselle','Pommes sauvages','Cresson de fontaine'],
          biv: 'Berges Moselle entre Toul et Charmes.' },
        { nom: 'Épinal → Corre → Vesoul (Canal des Vosges)', km: '~115 km / 3 j',
          voies: ['Canal des Vosges halage intégral'],
          note: 'Halage désert, écluse tous les 3–4 km — eau potable garantie, recharge VAE aux maisons éclusières.',
          cueil: ['Cèpes des Vosges — sous pins','Chanterelles — hêtraies','Cornouilles'],
          biv: 'Écluses entre Fontenoy-le-Château et Corre.' },
      ]
    },
    {
      num: 2, label: 'PARTIE 2 — DÉBUT SEPTEMBRE — Vesoul → Autun',
      mois: 'Début septembre', color: '#5a3a8a', km: '~255 km', jours: '~9 j',
      intro: 'Saône, Forêt de Chaux, Morvan. Cèpes et trompettes au pic. Transition vers le grand sud.',
      etapes: [
        { nom: 'Vesoul → Gray (berge Saône)', km: '~45 km / 2 j',
          voies: ['Halage Saône gravier','Chemins ruraux'],
          note: 'Chemin rural vers Scey-sur-Saône. Longer la Saône rive droite.',
          cueil: ['Mûres — fin de pic','Sureau noir','Noisettes — chute naturelle'],
          biv: 'Berges Saône entre Scey et Gray.' },
        { nom: 'Gray → Dole (Forêt de Chaux + Loue)', km: '~70 km / 2 j',
          voies: ['Pistes ONF Forêt de Chaux','VV de la Loue'],
          note: 'Traverser la Forêt de Chaux (20 000 ha) par pistes ONF — GPS indispensable. VV de la Loue jusqu\'à Dole.',
          cueil: ['Cèpes de Bordeaux — sous chênes : pic si pluies','Cèpe bronzé','Girolles','Cresson'],
          biv: 'Forêt de Chaux secteur Fraisans.' },
        { nom: 'Dole → Is-sur-Tille (canaux + pistes)', km: '~55 km / 2 j',
          voies: ['Canal Rhône-au-Rhin','Berge Saône aval'],
          note: 'Canal Rhône-au-Rhin jusqu\'à Auxonne, berges Saône vers Pontailler.',
          cueil: ['Cornouilles — rouge vif : pic septembre','Pommes et poires sauvages','Bolet bai'],
          biv: 'Écluses Canal Rhône-au-Rhin.',
          warn: '~10% D-routes Dole–Pontailler — traverser en semaine tôt le matin.' },
        { nom: 'Is-sur-Tille → Autun (VV Ouche + Morvan)', km: '~85 km / 3 j',
          voies: ['VV Ouche asphalte 40 km','Canal Bourgogne','Pistes ONF Morvan'],
          note: 'VV de l\'Ouche — 40 km en forêt sans voiture. Tunnel de Blaisy-Bas (4 km) : lampe frontale obligatoire.',
          cueil: ['Cèpes — Morvan : meilleure zone','Lactaires délicieux — sous pins','Trompettes de la mort','Noisettes'],
          biv: 'Forêt autour tunnel Blaisy-Bas.' },
      ]
    },
    {
      num: 3, label: 'PARTIE 3 — DÉBUT OCTOBRE → 10 NOVEMBRE — Autun → Hendaye',
      mois: 'Octobre → début novembre', color: '#3a6e28', km: '~985 km', jours: '~42 j',
      intro: 'Le grand sud. Rhône, Ardèche châtaignes, Corbières glands, Ariège, Piémont pyrénéen, Hendaye.',
      etapes: [
        { nom: 'Autun → Chalon (Canal du Centre)', km: '~80 km / 3 j',
          voies: ['Pistes Morvan sud','Canal du Centre halage'],
          note: 'Pistes forestières Morvan sud vers Montcenis, rejoindre le canal à Montceau-les-Mines.',
          cueil: ['Châtaignes Morvan — début récolte : objectif 3–4 kg','Cèpes — sous chênes et hêtres','Trompettes de la mort'],
          biv: 'Forêts Morvan sud entre Autun et Montcenis.' },
        { nom: 'Chalon → Lyon (ViaRhôna rive gauche)', km: '~130 km / 4 j',
          voies: ['ViaRhôna piste cyclable','Berge Saône / Rhône'],
          note: 'ViaRhôna quasi-continue jusqu\'à Lyon. Arrêt Lyon : ravitaillement, recharge VAE.',
          cueil: ['Noix — vergers en lisière','Pommes sauvages — haies bord Saône'],
          biv: 'Berges Saône entre Tournus et Mâcon.' },
        { nom: 'Lyon → Vienne — rive droite ardéchoise', km: '~43 km / 1 j',
          voies: ['Berge Rhône rive droite','D4 viticole très calme'],
          note: '⚡ BIFURCATION TRACÉ B. Traverser au pont de la Mulatière. Rive droite via Givors, chemin de berge vers Condrieu. Évite Feyzin/Solaize/Pierre-Bénite.',
          cueil: ['Noix — vergers Condrieu','Raisins sauvages — vignes abandonnées'],
          biv: 'Berges Rhône rive droite entre Givors et Condrieu.',
          warn: 'GPS chargé obligatoire — rive droite non balisée ViaRhôna sur 15 km.' },
        { nom: 'Vienne → Valence (ViaRhôna rive gauche)', km: '~100 km / 3 j',
          voies: ['ViaRhôna piste séparée'],
          note: 'Reprendre ViaRhôna rive gauche à Vienne. Piste séparée quasi-continue : Tournon, Tain-l\'Hermitage.',
          cueil: ['Noix — abondantes en lisière','Cornouilles — rouges et mûres'],
          biv: 'Berges Rhône entre Tournon et Valence.' },
        { nom: 'Tournon → Lamastre → Le Cheylard (Ardèche)', km: '~55 km / 3 j',
          voies: ['D9 vallée du Doux (calme)','Pistes ONF Monts d\'Ardèche'],
          note: 'Traverser le Rhône à Tournon. Monter D9 vallée du Doux. Zone la plus isolée du projet. Prévoir 2 jours stationnaires pour la récolte.',
          cueil: ['⭐ ZONE CHÂTAIGNES 1 — objectif 6–8 kg frais','Glands chêne sessile : lancer premier trempage','Cèpes — sous chênes','Trompettes — hêtraies d\'altitude'],
          biv: 'Forêt domaniale ONF entre Le Cheylard et Valgorge — 2 j stationnaires.',
          warn: '~5% nationales sur D9 — trafic très faible en semaine d\'octobre.' },
        { nom: 'Le Cheylard → Valgorge → Les Vans', km: '~60 km / 2 j',
          voies: ['Pistes forestières ONF','D5 vallée Beaume (calme)'],
          note: 'Descendre vers Largentière par la vallée du Beaume. Cœur des châtaigneraies communales abandonnées.',
          cueil: ['⭐ ZONE CHÂTAIGNES 2 — forêts communales Joyeuse/Les Vans','Arbres monumentaux 150–300 ans','Pied-de-mouton — sous châtaigniers'],
          biv: 'Vallée du Chassezac aux Vans.' },
        { nom: 'Les Vans → Alès → Ganges (Cévennes)', km: '~80 km / 3 j',
          voies: ['Pistes ONF Parc national','GR7 praticable VAE','Gorge Hérault'],
          note: 'Pistes forestières Parc national. Cueillette personnelle autorisée par charte du Parc national.',
          cueil: ['⭐ ZONE CHÂTAIGNES 3 — châtaigniers spontanés sauvages','Chêne pubescent — glands doux : 1–2 trempages','Coulemelles — prairies'],
          biv: 'Col de l\'Asclier — hêtraie-châtaigneraie, Parc national.' },
        { nom: 'Ganges → Montpellier → Béziers', km: '~110 km / 3 j',
          voies: ['VV Hérault partielle','Pistes agricoles Languedoc'],
          note: 'Descendre vallée Hérault. Contourner Montpellier par le nord. Garrigue — chêne pubescent et vert omniprésents.',
          cueil: ['Chêne pubescent — objectif 4–6 kg frais','Chêne vert — petits glands','Figues sauvages','Olives sauvages — à saumurer'],
          biv: 'Garrigue entre Clermont-l\'Hérault et Béziers.' },
        { nom: 'Béziers → Lézignan → Quillan (Corbières)', km: '~100 km / 3–4 j',
          voies: ['D-routes Corbières calmes','Vallée Aude encaissée'],
          note: '⚡ VARIANTE B — évite Canal du Midi venteux. Rejoindre la vallée de l\'Aude à Couiza. D118 jusqu\'à Quillan — route encaissée, abritée de la Tramontane.',
          cueil: ['Chêne pubescent — glands doux','Truffes noires — début saison sous chênes truffiers','Cèpes si pluies'],
          biv: 'Gorges de l\'Aude entre Couiza et Quillan.',
          warn: '~5% D-routes Corbières — trafic très faible.' },
        { nom: 'Quillan → Foix (vallée Ariège)', km: '~80 km / 3 j',
          voies: ['D-routes Pays de Sault','Vallée Ariège piste partielle'],
          note: 'Monter vers le Pays de Sault (col ~800 m). Descendre vers Ax-les-Thermes puis Foix. Vallées encaissées = abri contre Tramontane.',
          cueil: ['Châtaignes — versants pyrénéens : saison tardive','Cèpes — sous hêtres et sapins','Myrtilles séchées — fin de saison'],
          biv: 'Vallée de l\'Ariège entre Ax et Foix.',
          warn: 'Col Pays de Sault ~800 m : vérifier météo neige. Repli possible vallée Aude (+15 km).' },
        { nom: 'Foix → Saint-Girons → Saint-Gaudens (piémont)', km: '~90 km / 3 j',
          voies: ['Vallée Hers et Arize','Pistes agricoles piémont'],
          note: 'Vallée du Hers depuis Foix vers Pamiers. Traverser vers Saint-Girons. Remonter vers Saint-Gaudens par vallée du Salat.',
          cueil: ['Noix — vergers piémont','Châtaignes piémont','Cèpes de pins'],
          biv: 'Berges du Salat entre Saint-Girons et Saint-Gaudens.' },
        { nom: 'Saint-Gaudens → Tarbes → Pau', km: '~100 km / 3 j',
          voies: ['VV Gave de Pau partielle','D-routes agricoles piémont'],
          note: 'Longer la chaîne pyrénéenne par le piémont. VV du Gave de Pau depuis Lourdes. Vue sur les Pyrénées enneigées.',
          cueil: ['Noix — Bigorre : vergers nombreux','Prunelles — après premières gelées','Cèpes'],
          biv: 'Berges Gave de Pau entre Lourdes et Pau.' },
        { nom: 'Pau → Bayonne → Hendaye', km: '~110 km / 3–4 j',
          voies: ['VV Gave de Pau → Bayonne','EuroVelo 1 côte basque'],
          note: 'VV du Gave de Pau de Pau à Bayonne. EV1 côte basque jusqu\'à Hendaye. Arrivée ~10 novembre.',
          cueil: ['Moules de roche — rochers Socoa/Hendaye','Coques — plages sableuses','Bigorneaux','Crevettes grises'],
          biv: 'Dunes et pins entre Hossegor et Bayonne.',
          prot: ['Moules de roche — 5 kg/j max, usage personnel','Coques — 2–3 cm de sable humide','Pêche en mer sans permis — bar, mulet'] },
      ]
    }
  ]
};
